const T=[['home','Today'],['fleet','Fleet'],['suite','Suite'],['fatigue','Hours'],['load','Load'],['mass','Mass'],['owner','Owner']];
const note='<p class="note">Remember to log into Logmaster and Intellifleet. Suite documents are drafts.</p>';
const S={tab:'suite'};
function tabs(){document.getElementById('tabs').innerHTML=T.map(([id,l])=>`<button data-tab="${id}" class="${S.tab===id?'active':''}">${l}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render();});}
function render(){tabs();views[S.tab]();document.querySelectorAll('[data-go]').forEach(c=>c.onclick=()=>{S.tab=c.dataset.go;render();});}
const views={
home(){document.getElementById('view').innerHTML=`${note}<div class="cards"><div class="card" data-go="suite"><div class="kicker">Drive</div><h3>Document suite</h3><p>GSA, mass, fatigue and registers. All still draft.</p></div><div class="card" data-go="fleet"><div class="kicker">Fleet</div><h3>In service</h3><p>Four fridges. Quad still being built.</p></div><div class="card" data-go="fatigue"><div class="kicker">Hours</div><h3>Standard or BFM</h3><p>12 h or 14 h. Match Logmaster.</p></div><div class="card" data-go="load"><div class="kicker">Load</div><h3>0.8 / 0.5 / 0.2 g</h3><p>Restraint before departure.</p></div></div>`;},
suite(){document.getElementById('view').innerHTML=`${note}<div class="panel"><h2>MMJ suite, 2 Oct 2026</h2><p>Not approved yet. Open the folder, then the document. <a href="https://drive.google.com/drive/folders/1XFatbzdKVjHh28u6zhIQmHze5xZxsZX-" target="_blank">Full suite</a></p><table><tr><th>Folder</th><th>Use</th></tr><tr><td><a href="https://drive.google.com/drive/folders/1OqA_s9_2DMlJXW8thrbmcU7EIn02s9H_" target="_blank">00 Control and audit</a></td><td>Index, document register, audit schedule</td></tr><tr><td><a href="https://drive.google.com/drive/folders/1xaDHyZyEWGiG3ckHPFvtrs1lpOJXYPfv" target="_blank">01 SMS and CoR</a></td><td>Manual, policies, pre-start, speed, collision</td></tr><tr><td><a href="https://drive.google.com/drive/folders/1gziCvjqteM9Y_-hkuVj04E79kLuUqCtb" target="_blank">02 Mass</a></td><td>Mass manual, load sheet, weigh method, restraint</td></tr><tr><td><a href="https://drive.google.com/drive/folders/17CITpnW-uW7kHNnA_gxYqv9lD7RTb0Kp" target="_blank">03 Fatigue</a></td><td>Fatigue manual, roster rule, standard-hours position</td></tr><tr><td><a href="https://drive.google.com/drive/folders/19e0Bc3QXOqBDkyb8f51wIQ0fpxfel67D" target="_blank">04 Registers</a></td><td>Drivers, breaches, due diligence, risk</td></tr><tr><td><a href="https://drive.google.com/drive/folders/1qkP4fpyubFBJxhdZ2vnnHS1NjAyOBxqh" target="_blank">05 HVA application</a></td><td>Lodgement index and GSA map</td></tr></table><p>PBS — New Trailer is parked and is not part of the audit set. The quad is still being built.</p><p>Driver copies: <a href="https://drive.google.com/file/d/1aIlk7r-Ubw3_Z2Vn8zvJ7yixojoVzqqI/view" target="_blank">TRTS-005 Pre-start</a> · <a href="https://drive.google.com/file/d/1h7b81-T8N_fmGzjsJLHSy664XGWmfZpB/view" target="_blank">TRTS-008 CoR driver</a> · <a href="https://drive.google.com/file/d/1WlaegwkvLX4K2Kegqqko7tk9BRIxDiTg/view" target="_blank">TRTS-012 Fatigue</a> · <a href="https://drive.google.com/file/d/1-8MgehO7sFB1v--aVSPV_qCA_ssjZWxN/view" target="_blank">TRGP-009 Load restraint</a> · <a href="https://drive.google.com/file/d/1QaGc9T-Y4xm4-seHXsBGe-NkLwJXPMA4/view" target="_blank">DEC-003 Standard hours</a></p></div>`;},
fleet(){document.getElementById('view').innerHTML=`${note}<div class="panel"><h2>In service</h2><p>Prime movers MDJ200, MDJ201, 909MDJ, MDJ909, XO58FN. Fridges YN37NH, YN91MY, YN94WT, YO39HV. The 26-pallet quad is still being built and is not YN37NH.</p></div>`;},
fatigue(){document.getElementById('view').innerHTML=`${note}<div class="panel"><h2>Hours</h2><p>Standard 12 h. BFM 14 h only if inducted. Position is DEC-003 until BFM is granted. Logmaster is the diary.</p></div>`;},
load(){document.getElementById('view').innerHTML=`${note}<div class="panel"><h2>Load</h2><p>0.8 g forward, 0.5 g sideways and back, 0.2 g up. Method is TRGP-009. Load sheet is TRF-006.</p></div>`;},
mass(){document.getElementById('view').innerHTML=`${note}<div class="panel"><h2>Mass</h2><p>Current trailers use existing limits. Weigh method is TRGP-007. Quad has no Vehicle Approval.</p></div>`;},
owner(){document.getElementById('view').innerHTML=`${note}<div class="panel"><h2>Office</h2><p>Monthly pack is TRF-011. Due diligence register is REG-DD-001. Accreditation pathway is HVA-001. None of these are lodged yet.</p></div>`;}
};
document.getElementById('installBtn').onclick=()=>alert('iPhone: Share, Add to Home Screen.');
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
